from src.pipeline import load_data, select_feature_target, train_model, split_data, evaluate_model, prepare_data, plot_results, plot_actual_vs_predicted, plot_residuals
df = load_data("data/study_hours.csv")
X, y = select_feature_target(df, "hours_studied", "exam_score")
X_train, X_test, y_train, y_test = split_data(X,y)
model = train_model(X_train, y_train)
plot_actual_vs_predicted(model, X_test, y_test, "Study Hours: Actual vs Predicted")
plot_residuals(model, X_test, y_test, "Study Hours: Residuals")
plot_results(X, y, model, "Hours Studied", "Exam Score", "Study Hours: Actual vs Fitted line")
metrics = evaluate_model(model, X_test, y_test)
print(metrics)
print(model.coef_, model.intercept_)

df = load_data("data/housing.csv")
print(df.shape)
df= df[df["median_house_value"] < 500001]
df = prepare_data(df, "median_income", "median_house_value")
print(df.shape)
X, y = select_feature_target(df, "median_income", "median_house_value")
X_train, X_test, y_train, y_test = split_data(X,y)
model = train_model(X_train, y_train)
plot_actual_vs_predicted(model, X_test, y_test, "Housing: Actual vs Predicted")
plot_residuals(model, X_test, y_test, "Housing: Residuals")
plot_results(X, y, model, "Median House Income", "Median House Value", "Median House Icome vs Median House Value Regression line")
metrics = evaluate_model(model, X_test, y_test)
print(metrics)
print(model.coef_, model.intercept_)

